<?php
if (function_exists('acf_add_local_field_group')):

    acf_add_local_field_group(array(
        'key'                   => 'group_5e202023c014b',
        'title'                 => 'Sagsdata',
        'fields'                => array(
            array(
                'key'               => 'field_5e2020306dddb',
                'label'             => 'Generelt',
                'name'              => '',
                'type'              => 'tab',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'placement'         => 'top',
                'endpoint'          => 0,
            ),
            array(
                'key'               => 'field_5e202a27a34ff',
                'label'             => 'Navn',
                'name'              => 'name',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),
            array(
                'key'               => 'field_5e20346d4468b',
                'label'             => 'Dato',
                'name'              => 'dato',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),
            array(
                'key'               => 'field_5e20205b6dddc',
                'label'             => 'Sags ID',
                'name'              => 'caseKey',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),
            array(
                'key'               => 'field_5e20205k3l40o',
                'label'             => 'Shop no',
                'name'              => 'shopNo',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),
            array(
                'key'               => 'field_5e202a36a3500',
                'label'             => 'Url til dokument',
                'name'              => 'path',
                'type'              => 'url',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
            ),
            array(
                'key'               => 'field_5e2020896dddd',
                'label'             => 'Sagsnr',
                'name'              => 'caseNumber',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),
            array(
                'key'               => 'field_5e202084k5j6',
                'label'             => 'presentationUrl',
                'name'              => 'presentationUrl',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),
            array(
                'key'               => 'field_5e20209e6ddde',
                'label'             => 'Status',
                'name'              => 'status',
                'type'              => 'radio',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'choices'           => array(
                    'ACTIVE' => 'Aktiv',
                    'SOLD'   => 'Solgt',
                ),
                'allow_null'        => 0,
                'other_choice'      => 0,
                'default_value'     => '',
                'layout'            => 'vertical',
                'return_format'     => 'value',
                'save_other_choice' => 0,
            ),
            array(
                'key'               => 'field_5e20209e5k4j9',
                'label'             => 'Case Type',
                'name'              => 'caseType',
                'type'              => 'radio',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'choices'           => array(
                    'SalesCase' => 'SalesCase',
                    'RentalCase'   => 'RentalCase',
                    'BusinessSalesCase'   => 'BusinessSalesCase',
                    'BusinessRentalCase'   => 'BusinessRentalCase',
                    'LoanCase'   => 'LoanCase',
                ),
                'allow_null'        => 0,
                'other_choice'      => 0,
                'default_value'     => '',
                'layout'            => 'vertical',
                'return_format'     => 'value',
                'save_other_choice' => 0,
            ),
            array(
                'key'               => 'field_5e2020fe6dddf',
                'label'             => 'Reserveret',
                'name'              => 'reserved',
                'type'              => 'true_false',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'message'           => '',
                'default_value'     => 0,
                'ui'                => 1,
                'ui_on_text'        => '',
                'ui_off_text'       => '',
            ),
            array(
                'key'               => 'field_5e2020fek5l4k5',
                'label'             => 'Må ikke annonceres',
                'name'              => 'noAdvertisement',
                'type'              => 'true_false',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'message'           => '',
                'default_value'     => 0,
                'ui'                => 1,
                'ui_on_text'        => '',
                'ui_off_text'       => '',
            ),
            array(
                'key'               => 'field_5e2020fe6kd8',
                'label'             => 'Skjult',
                'name'              => 'hidden',
                'type'              => 'true_false',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'message'           => '',
                'default_value'     => 0,
                'ui'                => 1,
                'ui_on_text'        => '',
                'ui_off_text'       => '',
            ),
            array(
                'key'               => 'field_5e2025616de00',
                'label'             => 'Type',
                'name'              => 'propertyType',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),
            array(
                'key'               => 'field_5e2023226ddec',
                'label'             => 'Publiceringsdato',
                'name'              => 'publishedDate',
                'type'              => 'date_time_picker',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'display_format'    => 'd-m-Y H:i:s',
                'return_format'     => 'Y-m-d H:i:s',
                'first_day'         => 1,
            ),
            array(
                'key'               => 'field_5e2023596dded',
                'label'             => 'Solgt dato',
                'name'              => 'soldDate',
                'type'              => 'date_time_picker',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field'    => 'field_5e20209e6ddde',
                            'operator' => '==',
                            'value'    => 'SOLD',
                        ),
                    ),
                ),
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'display_format'    => 'd-m-Y H:i:s',
                'return_format'     => 'Y-m-d H:i:s',
                'first_day'         => 1,
            ),
            array(
                'key'               => 'field_5e202d28cc0fc',
                'label'             => 'Tilknyttet mægler',
                'name'              => 'realtor',
                'type'              => 'number',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'min'               => '',
                'max'               => '',
                'step'              => '',
            ),
            array(
                'key'               => 'field_5e202d283k4j5',
                'label'             => 'Mægler navn',
                'name'              => 'realtorName',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
            ),
            array(
                'key'               => 'field_5e202lk4m5n3',
                'label'             => 'Mægler email',
                'name'              => 'realtorEmail',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
            ),
            array(
                'key'               => 'field_5e20lokok546',
                'label'             => 'Mægler telefon',
                'name'              => 'realtorPhone',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
            ),
            array(
                'key'               => 'field_5e20l5k4j31',
                'label'             => 'Mægler mobil',
                'name'              => 'realtorMobile',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
            ),
            array(
                'key'               => 'field_5e200099k3k4m',
                'label'             => 'Mægler billede',
                'name'              => 'realtorImage',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
            ),
            array(
                'key'               => 'field_5e200l5k4j3k4',
                'label'             => 'Mægler title',
                'name'              => 'realtorTitle',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
            ),
            array(
                'key'               => 'field_5e20219f6dde2',
                'label'             => 'Adresse',
                'name'              => '',
                'type'              => 'tab',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'placement'         => 'top',
                'endpoint'          => 0,
            ),
            array(
                'key'               => 'field_5e2021a76dde3',
                'label'             => 'Vejnavn',
                'name'              => 'roadname',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),
            array(
                'key'               => 'field_5e203ac06dfbd',
                'label'             => 'Vejnummer',
                'name'              => 'roadnumber',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),
            array(
                'key'               => 'field_5e20286c404fb',
                'label'             => 'Adresse (Fritekst)',
                'name'              => 'addressFreetext',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),
            array(
                'key'               => 'field_5e20220a6dde4',
                'label'             => 'Etage',
                'name'              => 'floor',
                'type'              => 'number',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'min'               => '',
                'max'               => '',
                'step'              => '',
            ),
            array(
                'key'               => 'field_5e2022ac6dde7',
                'label'             => 'Dør',
                'name'              => 'door',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),
            array(
                'key'               => 'field_5e20225d6dde5',
                'label'             => 'Post nr.',
                'name'              => 'zipcode',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),
            array(
                'key'               => 'field_5e2022a06dde6',
                'label'             => 'By',
                'name'              => 'city',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),
            array(
                'key'               => 'field_5e2022bf6dde8',
                'label'             => 'Stednavn',
                'name'              => 'placename',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),
            array(
                'key'               => 'field_5e2022cc6dde9',
                'label'             => 'Kommune',
                'name'              => 'municipality',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),
            array(
                'key'               => 'field_5e2023056ddea',
                'label'             => 'Latitude',
                'name'              => 'latitude',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),
            array(
                'key'               => 'field_5e20230e6ddeb',
                'label'             => 'Longitude',
                'name'              => 'longitude',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),
            array(
                'key'               => 'field_5e20238e6ddee',
                'label'             => 'Arealer',
                'name'              => '',
                'type'              => 'tab',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'placement'         => 'top',
                'endpoint'          => 0,
            ),
            array(
                'key'               => 'field_5e20239f6ddef',
                'label'             => 'Boligareal',
                'name'              => 'sizeArea',
                'type'              => 'number',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'min'               => '',
                'max'               => '',
                'step'              => '',
            ),
            array(
                'key'               => 'field_5e2023b46ddf0',
                'label'             => 'Areal Total',
                'name'              => 'sizeAreaTotal',
                'type'              => 'number',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'min'               => '',
                'max'               => '',
                'step'              => '',
            ),
            array(
                'key'               => 'field_5e2023c66ddf1',
                'label'             => 'Grundareal',
                'name'              => 'sizeLand',
                'type'              => 'number',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'min'               => '',
                'max'               => '',
                'step'              => '',
            ),
            array(
                'key'               => 'field_5e2023d96ddf2',
                'label'             => 'Grundareal (ha)',
                'name'              => 'sizeLandHa',
                'type'              => 'number',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'min'               => '',
                'max'               => '',
                'step'              => '',
            ),
            array(
                'key'               => 'field_5e2023ec6ddf3',
                'label'             => 'Areal - Kælder',
                'name'              => 'sizeBasement',
                'type'              => 'number',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'min'               => '',
                'max'               => '',
                'step'              => '',
            ),
            array(
                'key'               => 'field_5e2023fe6ddf4',
                'label'             => 'Areal - Andre bygninger',
                'name'              => 'sizeOtherbuildingsTotal',
                'type'              => 'number',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'min'               => '',
                'max'               => '',
                'step'              => '',
            ),
            array(
                'key'               => 'field_5e2024136ddf5',
                'label'             => 'Areal - Udhus',
                'name'              => 'sizePatio',
                'type'              => 'number',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'min'               => '',
                'max'               => '',
                'step'              => '',
            ),
            array(
                'key'               => 'field_5e2024256ddf6',
                'label'             => 'Areal - Carport',
                'name'              => 'sizeCarport',
                'type'              => 'number',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'min'               => '',
                'max'               => '',
                'step'              => '',
            ),
            array(
                'key'               => 'field_5e2024536ddf7',
                'label'             => 'Areal - Garage',
                'name'              => 'sizeGarage',
                'type'              => 'number',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'min'               => '',
                'max'               => '',
                'step'              => '',
            ),
            array(
                'key'               => 'field_5e2024606ddf8',
                'label'             => 'Areal - Erhverv',
                'name'              => 'sizeCommercial',
                'type'              => 'number',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'min'               => '',
                'max'               => '',
                'step'              => '',
            ),
            array(
                'key'               => 'field_5e2024836ddf9',
                'label'             => 'Rum',
                'name'              => '',
                'type'              => 'tab',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'placement'         => 'top',
                'endpoint'          => 0,
            ),
            array(
                'key'               => 'field_5e2024906ddfa',
                'label'             => 'Antal - Rum',
                'name'              => 'numberRooms',
                'type'              => 'number',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'min'               => '',
                'max'               => '',
                'step'              => '',
            ),
            array(
                'key'               => 'field_5e2024a96ddfb',
                'label'             => 'Antal - Soveværelser',
                'name'              => 'numberBedrooms',
                'type'              => 'number',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'min'               => '',
                'max'               => '',
                'step'              => '',
            ),
            array(
                'key'               => 'field_5e2024b66ddfc',
                'label'             => 'Antal - Badeværelser',
                'name'              => 'numberBathrooms',
                'type'              => 'number',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'min'               => '',
                'max'               => '',
                'step'              => '',
            ),
            array(
                'key'               => 'field_5e2024d36ddfd',
                'label'             => 'Antal - Stuer',
                'name'              => 'numberLivingRooms',
                'type'              => 'number',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'min'               => '',
                'max'               => '',
                'step'              => '',
            ),
            array(
                'key'               => 'field_5e2024e16ddfe',
                'label'             => 'Antal - Etager',
                'name'              => 'numberFloors',
                'type'              => 'number',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'min'               => '',
                'max'               => '',
                'step'              => '',
            ),
            array(
                'key'               => 'field_5e2026686de08',
                'label'             => 'Tekster',
                'name'              => '',
                'type'              => 'tab',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'placement'         => 'top',
                'endpoint'          => 0,
            ),
            array(
                'key'               => 'field_5e2026716de09',
                'label'             => 'Overskrift',
                'name'              => 'title',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),
            array(
                'key'               => 'field_5e20268a6de0a',
                'label'             => 'Teaser',
                'name'              => 'teaser',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),
            array(
                'key'               => 'field_5e20268a6doske',
                'label'             => 'Annoncetekst 1',
                'name'              => 'description1',
                'type'              => 'wysiwyg',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),
            array(
                'key'               => 'field_5e20268a60i5u',
                'label'             => 'Annoncetekst 2',
                'name'              => 'description2',
                'type'              => 'wysiwyg',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),
            array(
                'key'               => 'field_5e20268a6dk5u',
                'label'             => 'Annoncetekst 3',
                'name'              => 'description3',
                'type'              => 'wysiwyg',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),
            array(
                'key'               => 'field_5e20264k3jl5k42',
                'label'             => 'Annoncetekst 4',
                'name'              => 'description4',
                'type'              => 'wysiwyg',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),
            array(
                'key'               => 'field_5e20264lok4095kdf',
                'label'             => 'Annoncetekst 5',
                'name'              => 'description5',
                'type'              => 'wysiwyg',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),
            array(
                'key'               => 'field_5e2026a76de0b',
                'label'             => 'Tag',
                'name'              => 'tag',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),
            array(
                'key'               => 'field_5e2026bb6de0c',
                'label'             => 'Keywords',
                'name'              => 'keywords',
                'type'              => 'taxonomy',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'taxonomy'          => 'post_tag',
                'field_type'        => 'multi_select',
                'allow_null'        => 0,
                'add_term'          => 1,
                'save_terms'        => 1,
                'load_terms'        => 1,
                'return_format'     => 'id',
                'multiple'          => 0,
            ),
            array(
                'key'               => 'field_5e20271e404f3',
                'label'             => 'Økonomi',
                'name'              => '',
                'type'              => 'tab',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'placement'         => 'top',
                'endpoint'          => 0,
            ),
            array(
                'key'               => 'field_5e20272e404f4',
                'label'             => 'Pris',
                'name'              => 'price',
                'type'              => 'number',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => 'kr',
                'min'               => '',
                'max'               => '',
                'step'              => '',
            ),
            array(
                'key'               => 'field_5e20273k4j68f',
                'label'             => 'Leje pr md.',
                'name'              => 'monthlyRent',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => [
                    array(
                        array(
                            'field' => 'field_5e20209e5k4j9',
                            'operator' => '==',
                            'value' => 'BusinessRentalCase'
                        ),
                    ),
                    array(
                        array(
                            'field' => 'field_5e20209e5k4j9',
                            'operator' => '==',
                            'value' => 'RentalCase'
                        ),
                    )
                ],
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
            ),
            array(
                'key'               => 'field_5e204k5j69f',
                'label'             => 'Årlig leje',
                'name'              => 'yearlyRent',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => [
                    array(
                        array(
                            'field' => 'field_5e20209e5k4j9',
                            'operator' => '==',
                            'value' => 'BusinessRentalCase'
                        ),
                    ),
                    array(
                        array(
                            'field' => 'field_5e20209e5k4j9',
                            'operator' => '==',
                            'value' => 'RentalCase'
                        ),
                    )
                ],
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
            ),
            array(
                'key'               => 'field_5e2044k5j67',
                'label'             => 'Årlig leje pr. kvm',
                'name'              => 'yearlyRentPrArea',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => [
                    array(
                        array(
                            'field' => 'field_5e20209e5k4j9',
                            'operator' => '==',
                            'value' => 'BusinessRentalCase'
                        ),
                    ),
                    array(
                        array(
                            'field' => 'field_5e20209e5k4j9',
                            'operator' => '==',
                            'value' => 'RentalCase'
                        ),
                    )
                ],
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
            ),
            array(
                'key'               => 'field_5e20272k5j6983',
                'label'             => 'ConnectionFee',
                'name'              => 'connectionFee',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
            ),
            array(
                'key'               => 'field_5e202775404f5',
                'label'             => 'Udbetaling',
                'name'              => 'downPayment',
                'type'              => 'number',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => 'kr',
                'min'               => '',
                'max'               => '',
                'step'              => '',
            ),
            array(
                'key'               => 'field_5e202794404f6',
                'label'             => 'Ejerudgifter (pr. md.)',
                'name'              => 'monthlyOwnerExpenses',
                'type'              => 'number',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => 'kr/md',
                'min'               => '',
                'max'               => '',
                'step'              => '',
            ),
            array(
                'key'               => 'field_5e2027d3404f7',
                'label'             => 'monthlyNetPayment',
                'name'              => 'monthlyNetPayment',
                'type'              => 'number',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => 'kr/md',
                'min'               => '',
                'max'               => '',
                'step'              => '',
            ),
            array(
                'key'               => 'field_5e2027e7404f8',
                'label'             => 'monthlyGrossPayment',
                'name'              => 'monthlyGrossPayment',
                'type'              => 'number',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => 'kr/md',
                'min'               => '',
                'max'               => '',
                'step'              => '',
            ),
            array(
                'key'               => 'field_5e2027f4404f9',
                'label'             => 'Prisreduktion (%)',
                'name'              => 'priceReductionPercent',
                'type'              => 'number',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '%',
                'min'               => '',
                'max'               => '',
                'step'              => '',
            ),
            array(
                'key'               => 'field_5e202814404fa',
                'label'             => 'Prisreduktion (dato)',
                'name'              => 'priceReductionDate',
                'type'              => 'date_time_picker',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'display_format'    => 'd-m-Y H:i:s',
                'return_format'     => 'Y-m-d H:i:s',
                'first_day'         => 1,
            ),
            array(
                'key'               => 'field_5e20289ca34fa',
                'label'             => 'Medier',
                'name'              => '',
                'type'              => 'tab',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'placement'         => 'top',
                'endpoint'          => 0,
            ),
            array(
                'key'               => 'field_5e20305dkk39e',
                'label'             => 'Billeder (eksterne)',
                'name'              => 'imagesExternal',
                'type'              => 'repeater',
                'instructions'      => '',
                'required'          => 0,
                'button_label'      => '',
                'layout'            => 'table',
                'sub_fields'        => [
                    array(
                        'key' => 'field_62bac1f273l2k',
                        'label'             => 'Sti',
                        'name'              => 'url',
                        'type'              => 'url',
                        'instructions'      => '',
                        'required'          => 0,
                    ),
                    array(
                        'key' => 'field_62bac1f27k4i3',
                        'label'             => 'Sti (tablet)',
                        'name'              => 'url_presentation',
                        'type'              => 'url',
                        'instructions'      => '',
                        'required'          => 0,
                    ),
                    array(
                        'key' => 'field_62bac1f279483',
                        'label'             => 'Sti (thumbnail)',
                        'name'              => 'url_thumbnail',
                        'type'              => 'url',
                        'instructions'      => '',
                        'required'          => 0,
                    ),
                    array(
                        'key' => 'field_62bac1f2d3291',
                        'label'             => 'Billedetekst',
                        'name'              => 'description',
                        'type'              => 'text',
                        'instructions'      => '',
                        'required'          => 0,
                    ),
                    array(
                        'key' => 'field_62bac1f4k45j64l',
                        'label'             => 'Prioritet',
                        'name'              => 'priority',
                        'type'              => 'text',
                        'instructions'      => '',
                        'required'          => 0,
                    ),

                ],
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'message'           => '',
                'default_value'     => '',
            ),
            array(
                'key'               => 'field_5e20305d93k45j',
                'label'             => 'Videoer (eksterne)',
                'name'              => 'videosExternal',
                'type'              => 'repeater',
                'instructions'      => '',
                'required'          => 0,
                'button_label'      => '',
                'layout'            => 'table',
                'sub_fields'        => [
                    array(
                        'key' => 'field_62bac1f272938',
                        'label'             => 'Sti',
                        'name'              => 'url',
                        'type'              => 'url',
                        'instructions'      => '',
                        'required'          => 0,
                    ),
                    array(
                        'key' => 'field_62bac1f272034',
                        'label'             => 'Mimetype',
                        'name'              => 'mimeType',
                        'type'              => 'text',
                        'instructions'      => '',
                        'required'          => 0,
                    ),
                ],
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'message'           => '',
                'default_value'     => '',
            ),
            array(
                'key'               => 'field_5e20305dkerod',
                'label'             => 'Plantegniner (eksterne)',
                'name'              => 'floorplansExternal',
                'type'              => 'repeater',
                'instructions'      => '',
                'required'          => 0,
                'button_label'      => '',
                'layout'            => 'table',
                'sub_fields'        => [
                    array(
                        'key' => 'field_62bac1f273l2k',
                        'label'             => 'Sti',
                        'name'              => 'url',
                        'type'              => 'url',
                        'instructions'      => '',
                        'required'          => 0,
                    ),
                    array(
                        'key' => 'field_62bac1f273291',
                        'label'             => 'Sti (tablet)',
                        'name'              => 'url_presentation',
                        'type'              => 'url',
                        'instructions'      => '',
                        'required'          => 0,
                    ),
                    array(
                        'key' => 'field_62bac1f273029',
                        'label'             => 'Sti (thumbnail)',
                        'name'              => 'url_thumbnail',
                        'type'              => 'url',
                        'instructions'      => '',
                        'required'          => 0,
                    ),
                    array(
                        'key' => 'field_62bac1f2d3291',
                        'label'             => 'Billedetekst',
                        'name'              => 'description',
                        'type'              => 'text',
                        'instructions'      => '',
                        'required'          => 0,
                    ),
                ],
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'message'           => '',
                'default_value'     => '',
            ),
            array(
                'key'               => 'field_5e7b0dc3432sd',
                'label'             => 'Galleri',
                'name'              => 'gallery',
                'type'              => 'gallery',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
            ),
            array(
                'key'               => 'field_5e7b0dc34o482',
                'label'             => 'Plantegninger',
                'name'              => 'drawingsGallery',
                'type'              => 'gallery',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
            ),
            array(
                'key'               => 'field_5e7b0dc34dk3a',
                'label'             => 'Fremhævetbillede 1',
                'name'              => 'featuredimage_1',
                'type'              => 'image',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'return_format'     => 'id',
                'default_value'     => '',
                'placeholder'       => '',
            ),
            array(
                'key'               => 'field_5e7b0dc3dkej3',
                'label'             => 'Fremhævetbillede 2',
                'name'              => 'featuredimage_2',
                'type'              => 'image',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'return_format'     => 'id',
                'default_value'     => '',
                'placeholder'       => '',
            ),
            array(
                'key'               => 'field_5e7b0dc3o4k75',
                'label'             => 'Fremhævetbillede 3',
                'name'              => 'featuredimage_3',
                'type'              => 'image',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'return_format'     => 'id',
                'default_value'     => '',
                'placeholder'       => '',
            ),
            array(
                'key'               => 'field_5e7b0dc3kjr8f',
                'label'             => 'Fremhævetbillede 4',
                'name'              => 'featuredimage_4',
                'type'              => 'image',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'return_format'     => 'id',
                'default_value'     => '',
                'placeholder'       => '',
            ),
            array(
                'key'               => 'field_5e7b0dc3k3j45',
                'label'             => 'Fremhævetbillede 5',
                'name'              => 'featuredimage_5',
                'type'              => 'image',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'return_format'     => 'id',
                'default_value'     => '',
                'placeholder'       => '',
            ),
            array(
                'key'               => 'field_5e7b0dc34ec14',
                'label'             => 'Primær Billede Thumbnail',
                'name'              => 'primaryPhoto',
                'type'              => 'url',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
            ),
            array(
                'key'               => 'field_5e7b0f24fd2f6',
                'label'             => 'Primær Billede 1000',
                'name'              => 'primaryPhoto1000',
                'type'              => 'url',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
            ),
            /*array(
                'key' => 'field_5e7b0f24f3k5s',
                'label' => 'Billeder 1000',
                'name' => 'photos1000',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
            ),
                array(
                    'key' => 'field_5e7b0f24f3dsd',
                    'label' => 'Billeder',
                    'name' => 'photos',
                    'type' => 'textarea',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                ),*/
            array(
                'key'               => 'field_5e20259c6de01',
                'label'             => 'Diverse',
                'name'              => '',
                'type'              => 'tab',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'placement'         => 'top',
                'endpoint'          => 0,
            ),
            array(
                'key'               => 'field_5e2025ad6de02',
                'label'             => 'Byggeår',
                'name'              => 'constructionYear',
                'type'              => 'number',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'min'               => '',
                'max'               => '',
                'step'              => '',
            ),
            array(
                'key'               => 'field_5e2025c06de03',
                'label'             => 'Ombygningsår',
                'name'              => 'reconstructionYear',
                'type'              => 'number',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'min'               => '',
                'max'               => '',
                'step'              => '',
            ),
            array(
                'key'               => 'field_5e2025d76de04',
                'label'             => 'Energimærke',
                'name'              => 'energyBrand',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),
            array(
                'key'               => 'field_5e2025e96de05',
                'label'             => 'Varmekilde',
                'name'              => 'heatingInstallation',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),
            array(
                'key'               => 'field_5e2025fa6de06',
                'label'             => 'Varmekilde (supplerende)',
                'name'              => 'heatingInstallationSuppl',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),
            array(
                'key'               => 'field_5e2026356de07',
                'label'             => 'Dage til salg',
                'name'              => 'daysForSale',
                'type'              => 'number',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'min'               => '',
                'max'               => '',
                'step'              => '',
            ),
            array(
                'key'               => 'field_5e20302a44687',
                'label'             => 'Åbent hus',
                'name'              => '',
                'type'              => 'tab',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'placement'         => 'top',
                'endpoint'          => 0,
            ),
            array(
                'key'               => 'field_5e20303644567',
                'label'             => 'Åbent hus aktiv',
                'name'              => 'openhouseActive',
                'type'              => 'true_false',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'message'           => '',
                'default_value'     => 0,
                'ui'                => 1,
                'ui_on_text'        => '',
                'ui_off_text'       => '',
            ),
            array(
                'key'               => 'field_5e20305a44689',
                'label'             => 'Tilmelding til åbent hus',
                'name'              => 'openhouseSignupRequired',
                'type'              => 'true_false',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field'    => 'field_5e20303644567',
                            'operator' => '==',
                            'value'    => '1',
                        ),
                    ),
                ),
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'message'           => '',
                'default_value'     => 0,
                'ui'                => 1,
                'ui_on_text'        => '',
                'ui_off_text'       => '',
            ),
            array(
                'key'               => 'field_5e20305ag5r2k',
                'label'             => 'Dato',
                'name'              => 'openHouseDate',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field'    => 'field_5e20303644567',
                            'operator' => '==',
                            'value'    => '1',
                        ),
                    ),
                ),
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'message'           => '',
                'default_value'     => '',
            ),
            array(
                'key'               => 'field_5e20305ag94k7',
                'label'             => 'Tilmeldingsfrist',
                'name'              => 'openhouseSignupDate',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field'    => 'field_5e20303644567',
                            'operator' => '==',
                            'value'    => '1',
                        ),
                    ),
                ),
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'message'           => '',
                'default_value'     => '',
            ),
            array(
                'key'               => 'field_5e20305dkleo9',
                'label'             => 'Datoer',
                'name'              => 'openhouseDatesTotal',
                'type'              => 'repeater',
                'instructions'      => '',
                'required'          => 0,
                'button_label'      => '',
                'layout'            => 'table',
                'sub_fields'        => [
                    array(
                      'key' => 'field_62bac1f27c19a',
                      'label'             => 'Dato start',
                      'name'              => 'dateStart',
                      'type'              => 'text',
                      'instructions'      => '',
                      'required'          => 0,
                    ),
                    array(
                        'key' => 'field_62bac1f2doek8',
                        'label'             => 'Dato slut',
                        'name'              => 'dateEnd',
                        'type'              => 'text',
                        'instructions'      => '',
                        'required'          => 0,
                    ),
                    array(
                        'key' => 'field_62bac1f2d93k8',
                        'label'             => 'Tilmelding',
                        'name'              => 'signupRequired',
                        'type'              => 'true_false',
                        'instructions'      => '',
                        'required'          => 0,
                        'ui'                => 1
                    ),
                    array(
                        'key' => 'field_62bac1f2dk4l3',
                        'label'             => 'ID',
                        'name'              => 'id',
                        'type'              => 'text',
                        'instructions'      => '',
                        'required'          => 0,
                    ),
                    array(
                        'key' => 'field_62bac1f24k5jd',
                        'label'             => 'Description',
                        'name'              => 'description',
                        'type'              => 'textarea',
                        'instructions'      => '',
                        'required'          => 0,
                    ),
                    array(
                        'key' => 'field_62bac1f23k4j5',
                        'label'             => 'dateStartUnix',
                        'name'              => 'dateStartUnix',
                        'type'              => 'text',
                        'instructions'      => '',
                        'required'          => 0,
                    ),
                    array(
                        'key' => 'field_62bac1f23l5k7',
                        'label'             => 'dateEndUnix',
                        'name'              => 'dateEndUnix',
                        'type'              => 'text',
                        'instructions'      => '',
                        'required'          => 0,
                    ),
                ],
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'message'           => '',
                'default_value'     => '',
            ),

        ),
        'location'              => array(
            array(
                array(
                    'param'    => 'post_type',
                    'operator' => '==',
                    'value'    => 'sag',
                ),
            ),
        ),
        'menu_order'            => 0,
        'position'              => 'normal',
        'style'                 => 'default',
        'label_placement'       => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen'        => '',
        'active'                => true,
        'description'           => '',
    ));

endif;